version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/planning_center_dev
      TEST_DATABASE_URL: postgresql://postgres:password@postgres:5432/planning_center_test
      REDIS_URL: redis://redis:6379
      TEST_REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-jwt-secret-change-in-production
      COOKIE_SECRET: dev-cookie-secret-32-characters-long
      ENCRYPTION_KEY: 12345678901234567890123456789012
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planning_center_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Create test database
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        sleep 10 &&
        psql -U postgres -c 'CREATE DATABASE planning_center_test;' || true
        wait
      "

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: